import "./css/style.css";

import { Inter } from "next/font/google";

import Header from "@/components/ui/header";
import Banner from "@/components/banner";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "InstaBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
        </div>
      </body>

      {/* <Script>
        {`window.embeddedChatbotConfig = {
          chatbotId: "A4oJ2GnJIW796AoFx3eEf",
          domain: "www.chatbase.co"
          }`}
      </Script>
      <Script
        src="https://www.chatbase.co/embed.min.js"
        // @ts-ignore
        chatbotId="A4oJ2GnJIW796AoFx3eEf"
        domain="www.chatbase.co"
        defer
      ></Script> */}

<Script>
{`window.embeddedChatbotConfig = {
chatbotId: "xgR2OU5u1Wp1pwbdYLOjo",
domain: "www.chatbase.co"}`
}
</Script>
<Script
src="https://www.chatbase.co/embed.min.js"
// @ts-ignore
chatbotId="xgR2OU5u1Wp1pwbdYLOjo"
domain="www.chatbase.co"
defer>
</Script>
    </html>
  );
}
